### PR TITLE
Restrict trinket use to unlock if disabled

### PR DESCRIPTION
**Pull request by BlueAgent**
Closes https://github.com/owmii/Lost-Trinkets/issues/59.

- Moved implementation of LostTrinkets API out of the api package.
- Prevent disabled trinkets from being unlocked from using a Trinket item.
- Add tooltip for disabled and non-random trinkets and ownership of trinket.
- Add support for config reloading (banned trinkets will be removed from online players when config is reloaded).

Feel free to squash before merging.

Screenshots:

Non-random Piggy Trinket
Non-random Piggy

Disabled Ash Gloves Trinket
Disabled Ash Gloves

Owned Turtle Shell Trinket
Owned Turtle Shell

Unowned but randomly obtainable Treasure Ring Trinket
Unowned but randomly obtainable Treasure Ring

### CODE REVIEW

**Comment by owmii** [comment]
Thank you!!

**Comment by owmii** [comment]
The lost trinket including this PR is not released yet because the mixin refmap won’t generate in the jar file.
Trying to find a fix sooner

**Comment by BlueAgent** [comment]
Found that downgrading to:

- Gradle Wrapper `4.10.3`
- Forge Gradle `3.+`

Has the refmap generate properly again.
This essentially reverts the update to Gradle Wrapper `6.8.1` and Forge Gradle `4.1.+` in https://github.com/owmii/Lost-Trinkets/commit/64e22946524eff00001b2998fc1a32d6f166b813.

Also tested with Gradle Wrapper `5.6.4 `and FG3 and it seems to also break with that.
Not quite sure what's going on though. Will try look into it but this may take a bit because I'm unfamiliar with MixinGradle and Gradle Plugin development in general.

**Comment by owmii** [comment]
Just downgraded to FG3 and gradle 4.10.3 and that fixed it.
Thanks for your response.

**Pull request merged**
